/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公開コンテンツ一覧取得
         * @description 公開されたコンテンツのみを返します。
         */
        get: {
            parameters: {
                query?: {
                    /** @description コンテンツタイプでフィルタリング */
                    type?: components["parameters"]["QueryType"];
                    /** @description フリーテキスト検索キーワード（例：タイトル/要約に対して） */
                    q?: components["parameters"]["QueryQ"];
                    /** @description ページサイズ */
                    limit?: components["parameters"]["QueryLimit"];
                    /** @description ページネーション用のオフセット */
                    offset?: components["parameters"]["QueryOffset"];
                    /** @description ソートフィールド */
                    sort?: components["parameters"]["QuerySort"];
                    /** @description ソート順 */
                    order?: components["parameters"]["QueryOrder"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ページネーションされた公開コンテンツのリスト */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContentListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** IDによる公開コンテンツ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description コンテンツID（UUID推奨） */
                    id: components["parameters"]["PathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 公開されたコンテンツアイテム */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Content"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Content: {
            /** Format: uuid */
            id: string;
            /** @description コンテンツタイプ識別子 */
            type: string;
            title: string;
            summary?: string | null;
            /** @description 記事の本文内容（記事タイプの場合に使用） */
            body?: string | null;
            /** @description メタデータ（JSON文字列として格納） */
            metadata: string;
            /**
             * Format: date-time
             * @description 公開タイムスタンプ
             */
            published_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ContentListItem: {
            /** Format: uuid */
            id: string;
            /** @description コンテンツタイプ識別子 */
            type: string;
            title: string;
            summary?: string | null;
            /** @description メタデータ（JSON文字列として格納） */
            metadata: string;
            /**
             * Format: date-time
             * @description 公開タイムスタンプ
             */
            published_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ContentListResponse: {
            items: components["schemas"]["ContentListItem"][];
            limit: number;
            offset: number;
            /** @description クエリの総件数（実装によっては近似値の場合があります） */
            total: number;
        };
        Error: {
            /** @example bad_request */
            code: string;
            /** @example 無効なパラメータ: limit */
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description 無効なリクエスト */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 見つかりません */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description コンテンツID（UUID推奨） */
        PathId: string;
        /** @description コンテンツタイプでフィルタリング */
        QueryType: string;
        /** @description フリーテキスト検索キーワード（例：タイトル/要約に対して） */
        QueryQ: string;
        /** @description ページサイズ */
        QueryLimit: number;
        /** @description ページネーション用のオフセット */
        QueryOffset: number;
        /** @description ソートフィールド */
        QuerySort: "created_at" | "updated_at" | "published_at" | "title";
        /** @description ソート順 */
        QueryOrder: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
